PRIMARY_ROAD_COLOR   = "#53b849"      
SECONDARY_ROAD_COLOR = "#139c4c"
TERTIARY_ROAD_COLOR  = "#5972FF"
SERVICE_ROAD_COLOR   = "#708090"

PRIMARY_PATH_COLOR   = "#0000FF"
PRIMARY_PATH_SEVERE_COLOR   = "#FF0000"
PRIMARY_PATH_MODERATE_COLOR   = "#FFA500"
PRIMARY_PATH_MINOR_COLOR   = "#0000FF"
SECONDARY_PATH_COLOR = "#6CC7E6"
SECONDARY_PATH_COLOR_SEVERE_COLOR = "#E78B69"
SECONDARY_PATH_COLOR_MODERATE_COLOR = "#F5DF66"
SECONDARY_PATH_COLOR_MINOR_COLOR = "#6CC7E6"

PATH_LINE_WIDTH      = 8
ROAD_LINE_WIDTH      = 4

# AI Model Constants
# List of available AI models. Add on more models here as needed.
ENUM_AI_MODELS       =["MobileNetV2", "ResNet50", "Xception"]

# Pathfinding Algorithm Constants
ENUM_PATHFIND_ALGORITHMS = ["All Algorithms", "A*", "Beam Search", "BFS", "DFS", "Dijkstra", "GBFS"]

# Test cases
TEST_CASE_FOLDER = "Test_Cases_Map"

#Running app configurations
OSM_FILEPATH = "map.osm"
MAX_CAMERA_COUNT = 30